HI IM BOB
MY FAVORITE COLOR IS <color="red">RED</color>!
I ALSO LIKE THIS SPECIFIC <color=\#005500>DARK GREEN</color>!
NOTE THAT THE ABOVE LINE HAS TO USE SLASH HASHTAG BEFORE THE HEX CODE BECAUSE INKY USES HASHTAG FOR SOMETHING ELSE
OK BYE NOW